# Generated by Django 5.1.4 on 2025-01-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='ticket_type',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='price',
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
