# Generated by Django 5.1.4 on 2025-01-13 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Event', '0002_remove_booking_ticket_type_remove_ticket_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='total_person',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
