# Generated by Django 5.1.4 on 2024-12-20 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ias_subscritions',
            name='is_active',
        ),
        migrations.AddField(
            model_name='ias_subscritions',
            name='device_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
