# Generated by Django 5.1.4 on 2024-12-21 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_ias_subscritions_is_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IAS_Subscritions',
            new_name='Licence_Keys',
        ),
    ]
